# Generated by Django 3.0.8 on 2021-03-17 00:09

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Survivor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default=None, max_length=120, validators=[django.core.validators.MinLengthValidator(2)])),
                ('age', models.DecimalField(decimal_places=0, default=None, max_digits=3, validators=[django.core.validators.MinValueValidator(0)])),
                ('gender', models.CharField(default=None, max_length=1, validators=[django.core.validators.MinLengthValidator(1)])),
                ('latitude', models.DecimalField(decimal_places=10, default=None, max_digits=12, validators=[django.core.validators.MaxValueValidator(90), django.core.validators.MinValueValidator(-90)])),
                ('longitude', models.DecimalField(decimal_places=10, default=None, max_digits=12, validators=[django.core.validators.MaxValueValidator(90), django.core.validators.MinValueValidator(-90)])),
                ('items', models.CharField(default=None, max_length=120, validators=[django.core.validators.MinLengthValidator(1)])),
                ('infected', models.BooleanField(default=False)),
                ('infection_marks', models.DecimalField(decimal_places=0, default=0, max_digits=2)),
            ],
        ),
    ]
