# Generated by Django 3.1.7 on 2021-03-17 22:50

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survivor', '0002_auto_20210317_2232'),
    ]

    operations = [
        migrations.AlterField(
            model_name='survivor',
            name='age',
            field=models.DecimalField(decimal_places=0, default=None, max_digits=3, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='survivor',
            name='name',
            field=models.CharField(default=None, max_length=120, validators=[django.core.validators.MinLengthValidator(2), django.core.validators.RegexValidator('^[a-zA-Z ]{2,70}$', 'Name must be 2 to 70 characters long and alphabetical')]),
        ),
    ]
