# Generated by Django 3.1.7 on 2021-03-18 00:00

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survivor', '0003_auto_20210317_2250'),
    ]

    operations = [
        migrations.CreateModel(
            name='FlagAsInfected',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('flaged_pk', models.CharField(max_length=120, validators=[django.core.validators.RegexValidator('^[0-9]*', 'Value must be numeric')])),
                ('flager_pk', models.CharField(max_length=120, validators=[django.core.validators.RegexValidator('^[0-9]*', 'Value must be numeric')])),
            ],
        ),
    ]
