# Generated by Django 3.1.7 on 2021-03-18 03:12

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survivor', '0004_flagasinfected'),
    ]

    operations = [
        migrations.CreateModel(
            name='TradeItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('buyer_pk', models.DecimalField(decimal_places=0, max_digits=10, validators=[django.core.validators.MinValueValidator(1)])),
                ('seller_pk', models.DecimalField(decimal_places=0, max_digits=10, validators=[django.core.validators.MinValueValidator(1)])),
                ('offered_items', models.CharField(max_length=120, validators=[django.core.validators.RegexValidator('^Fiji Water:[0-9]*;Campbell Soup:[0-9]*;First Aid Pouch:[0-9]*;AK47:[0-9]*$', "Correct stock declaration format: 'Fiji Water:x;Campbell Soup:x;First Aid Pouch:x;AK47:x'(include all fields even if you have 0)")])),
                ('requested_items', models.CharField(max_length=120, validators=[django.core.validators.RegexValidator('^Fiji Water:[0-9]*;Campbell Soup:[0-9]*;First Aid Pouch:[0-9]*;AK47:[0-9]*$', "Correct stock declaration format: 'Fiji Water:x;Campbell Soup:x;First Aid Pouch:x;AK47:x'(include all fields even if you have 0)")])),
            ],
        ),
    ]
