# Generated by Django 3.0.8 on 2021-03-19 02:15

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survivor', '0005_tradeitem'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reports',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('percentage_infected', models.CharField(max_length=120, validators=[django.core.validators.RegexValidator('^[0-9]*', 'Value must be numeric')])),
                ('percentage_healthy', models.CharField(max_length=120, validators=[django.core.validators.RegexValidator('^[0-9]*', 'Value must be numeric')])),
                ('average_water', models.CharField(max_length=120, validators=[django.core.validators.RegexValidator('^[0-9]*', 'Value must be numeric')])),
                ('average_soup', models.CharField(max_length=120, validators=[django.core.validators.RegexValidator('^[0-9]*', 'Value must be numeric')])),
                ('average_pouch', models.CharField(max_length=120, validators=[django.core.validators.RegexValidator('^[0-9]*', 'Value must be numeric')])),
                ('average_ak47', models.CharField(max_length=120, validators=[django.core.validators.RegexValidator('^[0-9]*', 'Value must be numeric')])),
                ('points_lost', models.CharField(max_length=120, validators=[django.core.validators.RegexValidator('^[0-9]*', 'Value must be numeric')])),
            ],
        ),
    ]
